apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkedlist-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: linkedlist
  template:
    metadata:
      labels:
        app: linkedlist
    spec:
      containers:
      - name: linkedlist
        image: linkedlist-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: linkedlist-service
spec:
  type: ClusterIP
  selector:
    app: linkedlist
  ports:
    - port: 5002
      targetPort: 5002