apiVersion: apps/v1
kind: Deployment
metadata:
  name: stack-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stack
  template:
    metadata:
      labels:
        app: stack
    spec:
      containers:
      - name: stack
        image: stack-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: stack-service
spec:
  type: ClusterIP
  selector:
    app: stack
  ports:
    - port: 5001
      targetPort: 5001